C $Header: /u/gcmpack/MITgcm_contrib/gael/verification/ECCO_v4_r2/code/AUTODIFF_OPTIONS.h,v 1.1 2014/10/20 03:29:00 gforget Exp $
C $Name:  $

CBOP
C !ROUTINE: AUTODIFF_OPTIONS.h
C !INTERFACE:
C #include "AUTODIFF_OPTIONS.h"

C !DESCRIPTION:
C *==================================================================*
C | CPP options file for AutoDiff (autodiff) package:
C | Control which optional features to compile in this package code.
C *==================================================================*
CEOP

#ifndef AUTODIFF_OPTIONS_H
#define AUTODIFF_OPTIONS_H
#include "PACKAGES_CONFIG.h"
#include "CPP_OPTIONS.h"

#ifdef ALLOW_AUTODIFF
#ifdef ECCO_CPPOPTIONS_H

C-- When multi-package option-file ECCO_CPPOPTIONS.h is used (directly included
C    in CPP_OPTIONS.h), this option file is left empty since all options that
C   are specific to this package are assumed to be set in ECCO_CPPOPTIONS.h

#else /* ndef ECCO_CPPOPTIONS_H */
C   ==================================================================
C-- Package-specific Options & Macros go here

C o Include/exclude code in order to be able to automatically
C   differentiate the MITgcmUV by using the Tangent Linear and
C   Adjoint Model Compiler (TAMC).
#define ALLOW_AUTODIFF_TAMC
C #undef AUTODIFF_TAMC_COMPATIBILITY (c68r)

C o Checkpointing as handled by TAMC
#define ALLOW_TAMC_CHECKPOINTING
C o DO 2-level checkpointing instead of 3-level
#undef AUTODIFF_2_LEVEL_CHECKPOINT
C o EXTEND 4-level checkpointing
C #undef AUTODIFF_4_LEVEL_CHECKPOINT (c68r)
  
C o Extract adjoint state
#define ALLOW_AUTODIFF_MONITOR
C o ... and DYNVARS_DIAG adjoint state
C #define ALLOW_AUTODIFF_MONITOR_DIAG (c68r)

C o use divided adjoint to split adjoint computations
#undef ALLOW_DIVIDED_ADJOINT
#undef ALLOW_DIVIDED_ADJOINT_MPI

C o Allow using viscFacInAd to recompute viscosities in AD
C   turned on for adjoint modeling (c68r-AD)
#define AUTODIFF_ALLOW_VISCFACADJ

C o To remove part of MOM_CALC_VISC (better name would be: MOM_DISABLE_*)
C #undef AUTODIFF_DISABLE_LEITH (c68r)
C #undef AUTODIFF_DISABLE_REYNOLDS_SCALE (c68r)

C o For output of AD-variables (ALLOW_AUTODIFF_MONITOR), specific code (e.g.,
C   in addummy_in_stepping.F) relies on adexch_uv_xy_rs and adexch_xy_rs S/R
C   which might not always be generated by TAF (e.g., when controls do not
C   include any 2D forcing field). In those cases, defining this cpp-option
C   allows to circumvent this missing code issue.
C #undef AUTODIFF_EXCLUDE_ADEXCH_RS (c68r)

C o Tape Settings
C - Tested and optimized by Gael Forget 
#define ALLOW_AUTODIFF_WHTAPEIO
#define AUTODIFF_USE_OLDSTORE_2D
#define AUTODIFF_USE_OLDSTORE_3D
#define EXCLUDE_WHIO_GLOBUFF_2D
#define ALLOW_INIT_WHTAPEIO

C   ==================================================================
#endif /* ndef ECCO_CPPOPTIONS_H */
#endif /* ALLOW_AUTODIFF */
#endif /* AUTODIFF_OPTIONS_H */

